name: GifHubActions Azure AD Token Demo

on:
  push:
    branches:
      - main

jobs:
  auth-azure:
    runs-on: ubuntu-latest

    permissions:
      id-token: write    
      contents: read

    steps:
      - name: 'Login to Azure with OIDC federated credentials'
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Show success message
        run: echo "Successfully authenticated with Azure using federated credentials!"

      - name: Get List of Folders
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            echo "Fetching all virtual directories..."
            
            # This command requests a single hierarchical layer using the delimiter
            # and filters for names ending in a trailing slash.
            FOLDERS=$(az storage fs file list \
                    --account-name "${{ secrets.AZURE_STORAGE_ACCOUNT }}" \
                    --file-system customers \
                    --auth-mode login \             
                    --output table)
              
            echo "Available folders:"
            echo "$FOLDERS"
